apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  DB_PASSWORD: S3c5OTAzMTgh
  ENCRYPT_SECRET_KEY: TlZOQ1dxNEtFREhYTmpzYXpkR1gyb1ox
  JWT_SECRET_KEY: MXdIcVFGZFVsVXI1VFpOcjF3VENpdXlNMFZ5ZTJMNGpY