apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-deployment
  labels:
    app: bank
    role: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
        role: microservice
    spec:
      nodeSelector:
        ng-type: private
      containers:
        - name: bank
          image: 086620157175.dkr.ecr.us-east-1.amazonaws.com/kwa-bank_microservice:latest
          imagePullPolicy: Always
          ports:
            - name: bank
              containerPort: 8083
          env:
            - name: APP_PORT
              value: "8083"
          envFrom:
            - configMapRef:
                name: env
            - secretRef:
                name: mysecret