apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
    role: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
        role: microservice
    spec:
      nodeSelector:
        ng-type: private
      containers:
        - name: user
          image: kw2000/user-microservice
          ports:
            - name: user
              containerPort: 8070
          env:
            - name: APP_PORT
              value: "8070"
          envFrom:
            - configMapRef:
                name: env
            - secretRef:
                name: mysecret