---
 - name: Working with AWS EC2 Instance
   hosts: localhost
   connection: local
   gather_facts: false
   tasks:
     - name: Create ec2 instance
       ec2:
         instance_type: t2.micro
         image: ami-0f9fc25dd2506cf6d
         count: 1
         key_name: kwa-ssh
         group: kwa-ansible-SG
         region: us-east-1
         instance_tags:
            Name: kwa-ansible-ec2